### ISSUE TITLE
suggestion: combine filters

### ISSUE THREAD

**Issue by rotsix** [project-mir/mir.qualia#2]
Hi!

First, thanks for this amazing soft bro <3

Simple suggestion, make it possible to combine filters (eg: `qualia laptop hostname` to uncomment both laptop and hostname comments).

Thanks bro!

**Comment by darkfeline** [comment]
That's already possible; have you tried it?

**Comment by rotsix** [comment]
A friend told me it wasn't but if you say it is, perfect! Thanks

**Comment by srhb** [comment]
@rotsix 
Didn't you mean to uncomment iff `laptop` AND `hostname` are present? I think the current behaviour is to uncomment if `laptop` OR `hostname` is present, but I may be mistaken.

**Comment by rotsix** [comment]
Here is an example:

`qualia laptop hostname` should return this:
```
# BEGIN laptop
foo
# END laptop
# BEGIN hostname
bar
# END hostname
# BEGIN server
# loremipsum
# END server
```

**Comment by srhb** [comment]
@rotsix 
My mistake, it absolute does work like that. :)
