### ISSUE TITLE
Support python <3.6

### ISSUE THREAD

**Issue by henniss** [project-mir/mir.qualia#3]
I use 3.6 at home, but at work I use some machines that are still only running 3.5. It would be nice to be able to use this without having to maintain user-local python installs for each one. 

Would it be possible to revert fe8244d48c86d66d827408b069e631bdf6f605f8?

**Comment by darkfeline** [comment]
Can you describe your use case more clearly?

1.0.0 supports Python 3.5.  That release is available on Github and PyPI.

**Comment by henniss** [comment]
Use case is I want to use this package without needing Python 3.6 installed. 1.0.0 works; thanks.
