### ISSUE TITLE
fail with non-utf8 files

### ISSUE THREAD

**Issue by rotsix** [project-mir/mir.qualia#4]
Hi mate.

I've encountered a new issue!

It seems that qualia doesn't like non-utf8 files (e.g. pics or w$ files).

Maybe it shouldn't check some files that aren't "readable" files?

Thanks!

**Comment by darkfeline** [comment]
qualia isn't intended to work on non-text files, same as grep, sed, etc.

If you're running into problems using Git filters, you can change your .gitattributes file to only match the text files you need to run qualia on.  That will make it faster too.

In theory qualia should work on non-utf8 text files, but I don't see a big use case for non-utf8, non-ASCII configuration files.  ASCII files are utf8 compatible anyway.

**Comment by rotsix** [comment]
Okep, then instead of telling qualia to ignore them, i'll tell it to git! seems clear, thanks!
